/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dyhodge' at '6/16/15 5:03 PM' with Gradle 2.4
 *
 * @author dyhodge, @date 6/16/15 5:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
